import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

/**
 * Generates a PDF for a published exam
 * @param {Object} exam - The exam object (title, instructions, duration, etc.)
 * @param {Array} questions - The approved questions for the exam
 * @param {String} outputPath - The path where the PDF should be saved
 * @returns {Promise<String>} - Returns the path of the generated PDF
 */
export const generateExamPDF = (exam, questions, outputPath) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const stream = fs.createWriteStream(outputPath);

            doc.pipe(stream);

            // --- Header ---
            doc.fontSize(20).text(exam.title || "Examination", { align: "center" });
            doc.moveDown(0.5);

            if (exam.subjects && exam.subjects.length > 0) {
                doc.fontSize(12).text(`Subject: ${exam.subjects.join(", ")}`, { align: "center" });
            }

            doc.fontSize(10).text(`Duration: ${exam.duration || "N/A"} minutes | Total Marks: ${exam.totalMarks || 0}`, { align: "center" });
            doc.moveDown(1);
            doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
            doc.moveDown(1);

            // --- Instructions ---
            if (exam.instructions) {
                doc.fontSize(14).text("Instructions:", { underline: true });
                doc.fontSize(10).text(exam.instructions);
                doc.moveDown(1);
            }

            // --- Questions ---
            doc.fontSize(14).text("Questions:", { underline: true });
            doc.moveDown(1);

            questions.forEach((q, index) => {
                // Question Text and Marks
                doc.fontSize(12).text(`${index + 1}. ${q.text}`, { continued: true });
                doc.fontSize(10).text(` (${q.marks} Marks)`, { align: "right" });
                doc.moveDown(0.5);

                // Options
                if (q.options && q.options.length > 0) {
                    q.options.forEach((opt, optIdx) => {
                        const label = String.fromCharCode(65 + optIdx); // A, B, C, D
                        doc.fontSize(10).text(`   ${label}) ${opt.text || opt}`);
                    });
                }
                doc.moveDown(1);

                // Check for page overflow
                if (doc.y > 650) {
                    doc.addPage();
                }
            });

            // --- Footer ---
            doc.fontSize(8).text(`Generated by Exam AI on ${new Date().toLocaleDateString()}`, {
                align: "center",
                bottom: 20
            });

            doc.end();

            stream.on("finish", () => {
                resolve(outputPath);
            });

            stream.on("error", (err) => {
                reject(err);
            });
        } catch (error) {
            reject(error);
        }
    });
};
